### ISSUE TITLE
Fails in instance generation within hva. (Error exec /etc/vz/conf/7260.mount: Text file busy)

### ISSUE THREAD

**Issue by k-oyakata** [axsh/wakame-vdc#109]
I, [2012-11-27T03:32:12.020413 #56102]  INFO -- HvaHandler: Session ID: 5d7b5a82b5127453c3937d7b36f125cb75c1a291: Instance UUID: i-i8kbnkw0: Created config /etc/vz/conf/7260.mount
I, [2012-11-27T03:32:12.020598 #56102]  INFO -- HvaHandler: Session ID: 5d7b5a82b5127453c3937d7b36f125cb75c1a291: Instance UUID: i-i8kbnkw0: Executing command: vzctl start i-i8kbnkw0
D, [2012-11-27T03:32:12.029859 #56102] DEBUG -- HvaHandler: Session ID: 5d7b5a82b5127453c3937d7b36f125cb75c1a291: Instance UUID: i-i8kbnkw0: Command Result: fail (exit code=79)
Command PID: 454514
##STDOUT=>
Starting container ...
##STDERR=>
Warning: distribution not specified in CT config, using defaults from /etc/vz/dists/default
Error exec /etc/vz/conf/7260.mount: Text file busy
Error executing mount script /etc/vz/conf/7260.mount
2012-11-27 03:32:12 JobContext thr=JobWorker[0/1] [ERROR]: Job failed 5d7b5a82b5127453c3937d7b36f125cb75c1a291 [ run_local_store ]: Unexpected exit code=79: vzctl start i-i8kbnkw0
Command PID: 454514
##STDOUT=>
Starting container ...
##STDERR=>
Warning: distribution not specified in CT config, using defaults from /etc/vz/dists/default
Error exec /etc/vz/conf/7260.mount: Text file busy
Error executing mount script /etc/vz/conf/7260.mount
2012-11-27 03:32:12 JobContext thr=JobWorker[0/1] [ERROR]: Caught Dcmgr::Helpers::CliHelper::ShellRunner::CommandError: Unexpected exit code=79: vzctl start i-i8kbnkw0
Command PID: 454514
##STDOUT=>
Starting container ...
##STDERR=>
Warning: distribution not specified in CT config, using defaults from /etc/vz/dists/default
Error exec /etc/vz/conf/7260.mount: Text file busy
Error executing mount script /etc/vz/conf/7260.mount
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/helpers/cli_helper.rb:180:in `block in run!'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/helpers/cli_helper.rb:178:in `tap'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/helpers/cli_helper.rb:178:in `run!'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/helpers/cli_helper.rb:95:in `sh'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/drivers/openvz.rb:272:in `run_instance'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:151:in `invoke!'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/task.rb:214:in `invoke'
        /opt/axsh/wakame-vdc/dcmgr/lib/dcmgr/rpc/hva_handler.rb:265:in `block in <class:HvaHandler>'
        /opt/axsh/wakame-vdc/dcmgr/vendor/bundle/ruby/1.9.1/gems/isono-0.2.17/lib/isono/runner/rpc_server.rb:69:in `instance_eval'

**Comment by Metallion** [comment]
Has been fixed.
