### ISSUE TITLE
GUI: an assignment state of security-groups is not refreshed in instance dialog.

### ISSUE THREAD

**Issue by YamazakiYasuhiro** [axsh/wakame-vdc#125]
An instance dialog is opened after pushing an "edit" button which is put beside instance list. The control of security-groups shows a state of current assignments. However the state seems to be kept whenever new dialog pops.

After some other menu which is put on left-side is clicked, you can open the instance dialog again and can see that the state was renewed.

**Comment by Metallion** [comment]
Has been fixed.
