### ISSUE TITLE
Re-organize Image data model and Image file generation process

### ISSUE THREAD

**Issue by unakatsuo** [axsh/wakame-vdc#141]
1. Add hypervisor field to images table.
2. Need to aware of OS distribution 

LoadBalancer Image
  * CentOS 6.3
  * Stud, AMQP tool

Test Image
  * CentOS6.3, Ubuntu 12.04
    * Hypervisor: KVM, ESXi, LXC, OpenVZ
  * Windows Server
    * Hypervisor: KVM, ESXi
  
Auto build folder structure
  * vmapp/

**Comment by Metallion** [comment]
Has been done.
