### ISSUE TITLE
GUI crashes when logging in without account

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#495]
### Problem

If you create a user and don't associate it with an account, logging in as that user will crash the GUI.

Reproduction:

* Create a user with no accounts associated.

```
/opt/axsh/wakame-vdc/frontend/dcmgr_gui/bin/gui-manage user add --name "user with no accounts" --uuid u-noacc --password noacc --login-id noacc
```

* Open up the GUI and log in with username `noacc` and password `noacc`.

The gui will crash with a nilclass exception since the users has no accounts associated.

### Solution

Check if the current username has any accounts associated with it and fail gracefully instead of crashing.

**Comment by hansode** [comment]
```
$ /opt/axsh/wakame-vdc/frontend/dcmgr_gui/bin/gui-manage user add --name "user with no accounts" --uuid u-noacc --password noacc --login-id noacc
uuid: u-noacc
login_id: noacc
password: noacc
```

**Comment by hansode** [comment]
![image](https://cloud.githubusercontent.com/assets/76867/7793683/35240baa-02fd-11e5-8402-0aacd29a597c.png)

**Comment by hansode** [comment]
and then webui restarted after applying #589.

**Comment by hansode** [comment]
![image](https://cloud.githubusercontent.com/assets/76867/7793740/e00b8e58-02fd-11e5-8d1d-a500ac550f5a.png)

**Comment by hansode** [comment]
not crashed.
