### ISSUE TITLE
Bug: IpLease::TYPE_RESERVED is undefined.

### ISSUE THREAD

**Issue by saicologic** [axsh/wakame-vdc#50]
IpLease::TYPE_RESERVED is undefined.
https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/endpoints/11.12/networks.rb#L83
https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/models/network.rb#L99-L102

Currentry move to Dcmgr::Models::NetworkVifIpLease::TYPE_RESERVED.
we need to revert to IpLease::TYPE_RESERVED from NetworkVifIpLease::TYPE_RESERVED

**Comment by Metallion** [comment]
API 11.12 is no longer supported.
