### ISSUE TITLE
Favicon needs to be improved

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#526]
The browser tab icon on the documentation website needs to be improved. Currently it's a Wakame logo with a white background and not perfectly square. Because of the latter it gets crushed when it shows up in a browser tab.

We need to replace it with a perfectly square icon with a transparent background.

**Comment by Mopster** [comment]
Updated with new icon : https://github.com/axsh/wakame-vdc/commit/49bc626aea8811e51e275e21b8c185443fc016a3

Waiting with new PR till mkdocs v0.12 and style update for the static site

**Comment by Metallion** [comment]
Favicon... So that's what they're called.

I don't see a reason to wait though. Let's merge it already.

**Comment by Metallion** [comment]
The favicon was update with this pull request. https://github.com/axsh/wakame-vdc/pull/528

I can see the favicon when serving locally but not after publishing on gh-pages yet.

**Comment by Mopster** [comment]
Because it's not in the source code, might be a bug with the template

**Comment by Metallion** [comment]
Looking at your issue on their repository, it seems like they fixed it in version 0.12.0. Upgrading mkdocs with pip brings it up to 0.12.2 so it should work now. Will confirm and then close this issue.

**Comment by Metallion** [comment]
Confirmed this to be fixed. Closing. Props to the mkdocs team for there effective response. :)
