### ISSUE TITLE
Windows instance password retrieval

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#552]
### Problem

When using a Windows instance, currently its (encrypted) password is stored in the 
database and returned every time the instance's data is requested from the WebAPI.

Even though it's encrypted, returning the password shouldn't returned automatically every time we want to know something about the instance. Also Wakame-vdc admins should have control over how long the encrypted password stays stored.

### Solution

* No longer return the password with the standard instance response. In other words, remove [this line](https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/endpoints/12.03/responses/instance.rb#L44). (Implemented in this commit: https://github.com/axsh/wakame-vdc/commit/5415981c23382d24826674653ff069b8ddf78601)
* Create a new WebAPI endpoint whose sole purpose is to retrieve Windows instance's passwords.
* Create the following section in `dcmgr.conf`.

```
windows {
  # When set to true, the Windows password will be deleted
  # from the database after being requested from the WebAPI once
  delete_password_on_request true

  # Set the time in minutes for the Windows password to remain
  # in the database. This timer starts running the moment the password
  # is first inserted in the database. When this time is expired, the password
  # will be deleted.
  # Set to 0 for unlimited.
  delete_password_after 60
}
```

(Implemented in commit:
https://github.com/axsh/wakame-vdc/commit/1fc55a4ccfedb8676042447d36aadcb2195909be
)

**Comment by Metallion** [comment]
This is what the new endpoint should look like.

#### Add  new WebAPI for Windows Password 
* location
  + wakame-vdc/dcmgr/lib/dcmgr/endpoints/12.03/instances.rb
* Retrieve Windows Password
  + Method
```
namespace '/:instance_id/password' do
  get '' do
    ...
  end
end
``` 
  +  Responses
     - instance uuid
     - password
  + Post processing
     - Clear the password field at specified instances record if the flag `delete_password_on_request` flag is set.

**Comment by triggers** [comment]
The writing in this issue is very helpful.  It's making things pretty
easy. Thanks.

Two questions:

(1) The comments like "# When set to true, the Windows..." are good.  Is
there an example dcmgr.conf in the Wakame-vdc repository anywhere
to put these in?  (find/grep says no)

(2) Is there any existing timer framework in Wakame-vdc that could be used
for implementing the delete_password_after functionality?  (have not
grepped for this yet...)

**Comment by Metallion** [comment]
(1) https://github.com/axsh/wakame-vdc/blob/master/dcmgr/config/dcmgr.conf.example

(2) https://github.com/axsh/wakame-vdc/blob/master/dcmgr/lib/dcmgr/helpers/cli_helper.rb#L69

**Comment by triggers** [comment]
Update:
This issue is mostly addressed by https://github.com/axsh/wakame-vdc/pull/579.
After addressing the comment by @unakatuo on May 26th, this pull request will
be ready for review (and merging).  (Automatic deletion of the encrypted password
will be addressed in the next pull request.)

**Comment by Metallion** [comment]
Has been implemented. https://github.com/axsh/wakame-vdc/pull/579
