### ISSUE TITLE
Windows password timed deletion

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#580]
### Problem

https://github.com/axsh/wakame-vdc/issues/552 talks about deleting a windows instance's password after a certain time has passed. This needs to be implemented.

### Solution

**New DB column**

Add a column to the `instances` table in the database called `password_will_be_deleted_at` and will be a DateTime type.

**New configuration option**

Create this configuration in dcmgr.conf

```
windows {
  # Set the time in minutes for the Windows password to remain
  # in the database. This timer starts running the moment the password
  # is first inserted in the database. When this time is expired, the password
  # will be deleted.
  # Set to 0 for unlimited.
  delete_password_after 60
}
```

**New NodeModule**

Implement a new NodeModule (thread) in Collector which will be in charge of deleting Windows passwords. That NodeModule will work like this:

* When collector starts

  1) Delete all passwords in the database whose `password_will_be_deleted_at` field is in the past.

  2) Select the `password_will_be_deleted_at` field that is closed to NOW() and in the future.

  3) Wait until that time and delete the password.

  4) Goto step 2

* When a new windows instance is created

  Goto step 2

**Comment by triggers** [comment]
Update:
This issue (plus part of https://github.com/axsh/wakame-vdc/issues/552) is addressed by this branch:
https://github.com/axsh/wakame-vdc/tree/windows-password-auto-deletion-tmp1
After  https://github.com/axsh/wakame-vdc/pull/579 is merged, I'll
rebase this branch and issue a pull request for it.

Note: the implementation is different from the specification above:

* delete_password_after is defined in hva.conf so hva can see it.
* deletion is done by polling in dcmgr/lib/dcmgr/node_modules/maintenance.rb

**Comment by triggers** [comment]
Pull request for this issue:
https://github.com/axsh/wakame-vdc/pull/606

**Comment by Metallion** [comment]
The pull request was merged but we are still writing further tests for this feature. This issue will stay open until said tests have been completed.

**Comment by Metallion** [comment]
On second thought, I'm going to open a new issue for the tests. I believe it's easier to keep track of our progress that way.
