### ISSUE TITLE
Split yum repository into development and stable

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#613]
### Problem

Currently we have one single yum repository for Wakame-vdc. This was ok since we only offered our current master branch to which all feature branches were merged directly.

When we release Version 1.0, we will implement semantic versioning and thus have both a stable and a development version.

### Solution

https://github.com/axsh/wakame-vdc/issues/614 should be completed first.

1. [x] Have the current rpmbuild CI job build packages from the branch `develop` instead of master.
2. [x] Create a new yum repository for stable releases.
3. [ ] Create a new CI job that builds the rpm packages for said stable release. We have made a CI job like this for OpenVNet and this one should behave in the same way.

  * Version numbers will be assigned using `git tag` on every commit of a master branch.
  * The stable package build job will be done manually and take `version` as a parameter.
  * The job should then checkout the provided tag and build RPM packages from there.

**Comment by hansode** [comment]
> Have the current rpmbuild CI job build packages from the branch develop instead of master.

done.

**Comment by hansode** [comment]
Updated jenkins rpmbuild project to support specified tag.

**Comment by hansode** [comment]
https://github.com/axsh/wakame-vdc/compare/feature-rpmbuild-rpm-version will be new pull-request for this issue.

**Comment by hansode** [comment]
now, the yum repository upload project can upload to release branch folder.

+ `http://dlc.wakame.axsh.jp/packages/rhel/6/release/:tag/:release_id/`
+ `http://dlc.wakame.axsh.jp/packages/rhel/6/release/:tag/current/`

**Comment by Metallion** [comment]
The packages in the **development** repository should be named like this (pretty much no change from current behaviour):

```
wakame-vdc-hva-common-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-hva-lxc-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-hva-openvz-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-bksta-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-client-mussel-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-dcmgr-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
wakame-vdc-webui-vmapp-config-1.0-20150728145643git7104b71.el6.noarch.rpm
```

On the **stable** repository, the date and git commit needs to be removed. Therefore they will be named like this:

```
wakame-vdc-hva-common-vmapp-config-1.0.el6.noarch.rpm
wakame-vdc-hva-lxc-vmapp-config-1.0.el6.noarch.rpm
wakame-vdc-hva-openvz-vmapp-config-1.0.el6.noarch.rpm
wakame-vdc-bksta-vmapp-config-1.0.el6.noarch.rpm
wakame-vdc-client-mussel-1.0.el6.noarch.rpm
wakame-vdc-dcmgr-vmapp-config-1.0.el6.noarch.rpm
wakame-vdc-webui-vmapp-config-1.0.el6.noarch.rpm
```

**Comment by hansode** [comment]
btw. at least revision number should be included like following.

```
- wakame-vdc-hva-common-vmapp-config-1.0.el6.noarch.rpm
+ wakame-vdc-hva-common-vmapp-config-1.0-1.el6.noarch.rpm
```

**Comment by Metallion** [comment]
Right. I agree about the last revision number.

**Comment by hansode** [comment]
for example, some rpm packages for rhel6 include git hash in revision part.

```
tcpdump-4.0.0-3.20090921gitdf3cb4.2.el6.x86_64
libpcap-1.0.0-6.20091201git117cb5.el6.x86_64
```

i referenced these number style.

**Comment by hansode** [comment]
i think current revision number policy should be kept.

**Comment by hansode** [comment]
what i want to say is including git commit hash is not invalid.

**Comment by Metallion** [comment]
I agree that it is not invalid. I think it is a very good idea for the development repository and our release style up until now but for our new stable release style, I think it is better to do it without. That way the stable releases will match the style here: http://mirror.centos.org/centos/6/os/x86_64/Packages/

**Comment by Metallion** [comment]
Another remark:

The git tags should not be used to set VDC_VERSION_TAG in the rpmbuild/rules file. This line in `wakame-vdc.spec` should decide the RPM package version. https://github.com/axsh/wakame-vdc/blob/develop/rpmbuild/SPECS/wakame-vdc.spec#L11

The git tag should only be used to do a `git checkout`. After that we should use whatever version is in `wakame-vdc.spec`.

That way a tag named `v1.0` will not cause the RPMs to be named "wakame-vdc-hva-common-vmapp-config-**v**1.0.el6.noarch.rpm"

**Comment by Metallion** [comment]
Some comments on the current job:

* It places packages under http://dlc.wakame.axsh.jp/packages/rhel/6/releases/1.0/. This is ok for testing release candidates but not for the main stable repo. The main repository for stable releases should be:

```
http://dlc.wakame.axsh.jp/packages/rhel/6/releases/master/current
```

The main repository for development releases should be

    http://dlc.wakame.axsh.jp/packages/rhel/6/releases/develop/current

That's how it currently is done in OpenVNet.

* The job needs an extra checkbox to update http://dlc.wakame.axsh.jp/packages/rhel/6/releases/master/current.

* The job should not ask you to set the rpm version and specify a branch. It should ask you to specify a github tag. When we release a new version, we will always add a tag and write the version number in the RPM specs. The job should do a "git checkout <tag>" and then rpmbuild using the version specified in the .spec files.

* The "20150728145643git7104b71" part needs to be removed for stable releases. The github tag is enough to track the exact commit of a stable release. In the development release, it needs to stay.

**Comment by Metallion** [comment]
Done.
