### ISSUE TITLE
Create a new default branch: develop

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#614]
### Problem

Since we're adopting the semantic versioning strategy, we need to keep our stable and development branch separate.

### Solution

We will use the same naming as OpenVNet.

* `master`: This branch will contain the stable release
* `develop`: All feature branches will be merged to this one. When a stable release is done, develop will be merged to master. If develop needs to continue with new features that won't be in the next stable release, a release candidate branch will be used.

**Comment by hansode** [comment]
```
$ git checkout -b develop
Switched to a new branch 'develop'
```

```
$ git push origin develop
To git@github.com:axsh/wakame-vdc
 * [new branch]      develop -> develop
```

**Comment by hansode** [comment]
![options](https://cloud.githubusercontent.com/assets/76867/8128872/3e770af0-113e-11e5-9ea2-70a90bdb104c.png)

**Comment by hansode** [comment]
![options](https://cloud.githubusercontent.com/assets/76867/8129014/990ae5bc-113f-11e5-8ad3-3f893116f977.png)

**Comment by Metallion** [comment]
Thank you, kind sir. :)
