### ISSUE TITLE
wakame-vdc does not create the meta-data\first-boot file required for booting Windows

### ISSUE THREAD

**Issue by triggers** [axsh/wakame-vdc#639]
### Background

When a Windows instance is restored from a backup object, a new random password is supposed to be generated.  If sysprep was run before making the backup object, then the password will be correctly generated, because Windows' first boot process ends by calling the wakame-init-first-boot.ps1 script, which always generates a password.  If sysprep was not run, then the wakame-init-every-boot.ps1 script will check if a file named "first-boot" exists on the meta-data drive.  If so then a new random password is generated. 

### Problem

Wakame-vdc is supposed to create the "first-boot" file when creating an instance from a backup object, just in case the machine image has not been sysprep'ed.  Currently, it does not create this file.

**Comment by triggers** [comment]
### Debugging

This seems to be the line that decides whether to create the first-boot file:

https://github.com/axsh/wakame-vdc/blob/develop/dcmgr/lib/dcmgr/metadata.rb#L13

**Comment by triggers** [comment]
Added debugging lines:
```
# Windows instances that don't have a password generated yet
  # need to be told to generate one.
  p "11111111111111111 #{password.nil?.inspect}"
  p "2222222222222211111111111111111 #{password.inspect}"
  p "eeeeeeee2222222222222211111111111111111 #{os_type.inspect}"
  if os_type == I::OS_TYPE_WINDOWS && password.nil?
    p "yyyyyyyyyyyyyy"
    AWSWithFirstBoot.new(instance_hash)
  else
    p "zzzzzzzzzzzzzzzzz"
    AWS.new(instance_hash)
  end
end
```
Launched with:
```
http_proxy= MUSSEL_RC=./MUSSEL_RC_WINDOWS ~/wakame-vdc-mita/client/mussel/mussel.sh instance create  --host_node_id=hn-dsv0004  --ssh-key-id ssh-cg5uukxl  --vifs=./vifs.txt
```
with this image, which is a non-sysprepp'ed backup object:
```
/ssh:m47: #$ cat MUSSEL_RC_WINDOWS | grep image
image_id=wmi-yfsxfaes
```

**Comment by triggers** [comment]
Result in the hva.log:
```
I, [2015-06-25T21:29:25.990848 #23159]  INFO -- HvaHandler: Session ID: 127f00a4712b5c1fb0ed3b42837d91a4bfc41ec6: Instance UUID: i-4yv7jhs6: Booting instance
"11111111111111111 false"
"2222222222222211111111111111111 \"\""
"eeeeeeee2222222222222211111111111111111 \"windows\""
"zzzzzzzzzzzzzzzzz"
```

**Comment by triggers** [comment]
Tentative conclusion: 
instance_hash[:encrypted_password] returns an empty string, so the test for .nil? is probably incorrect.

Note: When fixing this, it will be important to consider interactions with the new password auto-delete feature.

**Comment by Metallion** [comment]
Indeed Wakame-vdc judges whether or not a Windows instance is booted for the first time by checking if a password has been generated yet.

I will fix it so the backup procedure sets the password to nil indeed we should be careful about the auto-delete feature. The simple solution would be to have that set an empty string but it is very easy to forget why we did so in the future.

Another possible solution would be a first_boot column in the instance database or a special `first_boot` status for Windows instances.

**Comment by Metallion** [comment]
After a discussion with @unakatsuo, the idea came up to identify the place in the code where instances are booted for the first time and pass in a flag to the `setup_metadata_drive` method there.
