### ISSUE TITLE
Make an official Ubuntu machine image

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#689]
We currently have the tools to create an Ubuntu machine image for Wakame-vdc but we don't have one available for download. We should create one and make it available.

**Comment by Metallion** [comment]
We should make 2 images.

Image 1:
  * Allows password login
  * Username: ubuntu
  * Password: ubuntu

Image 2:
  * Doesn't allow password login
  * Username: ubuntu
  * Password: /

**Comment by t-iwano** [comment]
I just finished image 1 and image 2.

https://github.com/axsh/wakame-vdc/tree/feature-ubuntu-official-image

**Comment by t-iwano** [comment]
元イメージのマイナーバージョンが14.04.2だったので3に上げました。

https://github.com/t-iwano/ubuntu-minimal-image

アップロード先は以下。
http://dlc.wakame.axsh.jp/uservm/ubuntu-minimal-image/current/ubuntu-14.04.3-30g.kvm.box

TODO:
元イメージを自動で作れるようにする必要がある。内容検討。

**Comment by t-iwano** [comment]
最新版

https://github.com/axsh/wakame-vdc/tree/feature-ubuntu-official-image/vmapp

**Comment by t-iwano** [comment]
残タスク:
* jenkinsに登録して自動で作れるようにする。


追加予定ジョブ
* ubuntu official image build job
* upload to dropbox job

**Comment by t-iwano** [comment]
http://ci.wakame.jp/view/p.vdc.pub/view/build/job/ubuntu-image-build/

**Comment by Metallion** [comment]
Nice. :) :clap:

**Comment by t-iwano** [comment]
スパースファイルかつtgzに変更する。
```
Andreas Kieckens
19:08
cp --sparse=always ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw_old ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw
tar -Sczf ubuntu-14.04.3-x86_64-30g-passwd-login-enabled.raw.tgz ubuntu-14.04.3-x86_64-30g-passwd-login-enabled
```

**Comment by t-iwano** [comment]
tgzに変えてdropboxにuploadするようにjobを変更した。

**Comment by Metallion** [comment]
Done.
