### ISSUE TITLE
Split the Windows password API endpoint

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#693]
### Problem

Our current feature that deletes Windows password after they have been retrieved does not conform to RESTful API standards. Currently it is possible for an HTTP GET request to modify the database. This should not happen in a RESTful API

### Solution

- [x] Remove the auto-deletion option from dcmgr.conf.
- [x] Remove the code that deletes the password from `GET instances/i-xxxx/password`.
- [x] The above API route should fail with a `HTTP 410` code if the password in the database is NULL.
- [x] Implement a new API call `DELETE instances/i-xxxx/password` that deletes the password from the database. (sets it to NULL)
- [x] Implement a `delete_password` task to mussel.

**Comment by triggers** [comment]
```
[root@ct32 sysope]# mussel instance
instance             instance_monitoring  
[root@ct32 sysope]# mussel instance de
delete_password  destroy          
[root@ct32 sysope]# mussel instance show
show           show_password  
[root@ct32 sysope]# mussel instance show_password i-
i-2gubnxer  i-jakoaddk  i-z0ll6ihq  
[root@ct32 sysope]# mussel instance show_password i-2gubnxer 
---
:id: i-2gubnxer
:encrypted_password: |
  OQenuhl0tE0P4yfzkCsSH+ZVENf0DW0XtggR/Fy5KtTcJ0LYZDMpg3e8kuav
  K184a91ZGhSvGWVpRpG3ouUNd2EwT0VCnmmrhYJTDMsYfYIWDogsYCWgt17o
  i+T5oLub7HNRpWP6TCPonWw/ONi78RCEbP9xCAj2hO8o0P5jgLnHSJG1K+vt
  V+QIQGFXhiS0ytWng6PdPVJ2ZY67cizB5FbYjTdtvLJdObkjDfI58iaoYx1l
  Sx9x/5YVg3A/iNYcX0Sdb3odqW/3ejkSZkwbZ4ZFobqDwqfOwAmtYsSAU9My
  IeQQnKTtUbuUQCNIoxRvIHU0oTYbzrGXiOEx2zzV6g==
[root@ct32 sysope]# mussel instance de
delete_password  destroy          
[root@ct32 sysope]# mussel instance delete_password i-2gubnxer 
--- {}
[root@ct32 sysope]# mussel instance show_password i-2gubnxer 
curl: (22) The requested URL returned error: 410 Gone
[root@ct32 sysope]# mussel instance show_password i-metal    
curl: (22) The requested URL returned error: 404 Not Found
[root@ct32 sysope]# 
```

**Comment by triggers** [comment]
All above is implemented in:
https://github.com/axsh/wakame-vdc/pull/700
