### ISSUE TITLE
Mussel windows password decryption

### ISSUE THREAD

**Issue by Metallion** [axsh/wakame-vdc#707]
### Problem

Currently we have this script for decrypting windows passwords. https://github.com/axsh/wakame-vdc/blob/develop/dcmgr/script/decrypt_windows_password.sh

It's a very basic script that does little in the form of argument validation etc. It would be more convenient if mussel had Windows password decryption built in.

### Solution

Add a feature to mussel that decrypt windows passwords.

```
mussel instance decrypt_password i-abcde /path/to/private/key.pem
```

**Comment by triggers** [comment]
Implemented by https://github.com/axsh/wakame-vdc/pull/713

**Comment by Metallion** [comment]
Done.
