### ISSUE TITLE
Natbox: Update Open vSwitch to 2.4.0

### ISSUE THREAD

**Issue by hansode** [axsh/wakame-vdc#715]
### Background

I tried to install wakame-vdc packages on centos-6.7 but failed it. Because we don't have kmod-openvswitch.rpm built on centos-6.7.
CentOS-6.4 later includes `openvswitch.ko` in linux vanilla kernel package. We can use not our kmod-openvswitch but openvswitch.ko.

Under Open vSwitch 2.4.0's openvswitch.rpm depends on kmod-openvswitch.rpm.
Open vSwitch 2.4.0`s openvswtich.rpm does not depend on kmod-openvswitch.rpm.
Therefore we should use openvswitch-2.4.0 later. Currently Open vSwitch release version is 2.4.0.

### Problem

If wakame-vdc user install natbox on CentOS-6.7, the installation will be failed.
The detail error log is in #702.

### Possible solution

+ [ ] Update Open vSwitch to 2.4.0
+ [ ] Update rpmspec file.

**Comment by Metallion** [comment]
Done.
