### ISSUE TITLE
lxc-createにはオプション-tが必要

### ISSUE THREAD

**Issue by habuka036** [axsh/wakame-vdc#762]
OS: CentOS 6.7 x86_64
LXC: lxc-1.0.8
Wakame-vdc: 16.1.0

このバージョンの lxc-create では -t オプションが必須であり、-t オプションを付けずに実行すると以下のエラーが出る。

```
A template must be specified.
Use "none" if you really want a container without a rootfs.
```

よって、lxc.rbでlxc-createを実行している部分で

```
sh("lxc-create -t /bin/true -f %s -n %s", [ctx.lxc_conf_path, ctx.inst[:uuid]])
```

とすることで回避可能。
ただし他の問題が発生しないかどうかは未確認。

また、-t オプションが必須になったのはどのバージョンからなのか不明。

**Comment by Metallion** [comment]
issueを書いてくれて有難うございます！:) 今すぐ修正する暇がありませんが、もしpull requestをしてもらえれば、CIで動作確認出来ます。

**Comment by habuka036** [comment]
ありがとうございます。手元でテストして問題がクリアになったら PR 投げますので、気長にお待ちください :)

**Comment by habuka036** [comment]
lxc-create コマンドに -t オプションをつける改修案が3つあります。
- A案) hva.conf で lxc-create コマンドのオプションを設定できるようにする
- B案) kvm.rb の initialize で起動時に lxc-create コマンドのオプションを調べて、必要ならば -t オプションを付けるようにする
- C案) kvm.rb で vm を作成するたびに B 案と同様の処理を行なう

個人的な意見では以下の理由により B 案が一番望ましいと考えます。
- A案) 安易に設定ファイルで解決するようにすると OpenStack の nova.conf のようになってあまり好ましくない
- B案) hva が動いているときに lxc をアップデートした場合、オプションの仕様に変更があった場合に追従できない
- C案) B案のような状況でもオプションの仕様変更に対応できるが、vm が起動する毎にオプションを調べるため、vm 起動のオーバーヘッド大きくなる
