### ISSUE TITLE
Instanceにvifが設定できない

### ISSUE THREAD

**Issue by k-chino** [axsh/wakame-vdc#767]
terraform-providerブランチを使用し、templateのinstance部分にvifを追加しplanを実行してみました。
しかし、vifをkeyとして認識せずエラーが発生いたしました。

```
resource "wakamevdc_instance" "web_server" {
  cpu_cores = 1
  memory_size = 512
  hypervisor = "kvm"
  image_id = "wmi-centos1d64"
  ssh_key_id = "ssh-z75a0no9"
  description = "My web server"
  display_name = "WebServer"

  vif {
    network_id = "${wakamevdc_network.main.id}"
  }
}
```

```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * wakamevdc_instance.web_server: : invalid or unknown key: vif
```

**Comment by Metallion** [comment]
ネットワークIDぐらいは出来るようになりました。https://github.com/axsh/wakame-vdc/commit/784eb7147fea9dfeea1b77ac2a2c7a89caaf78c3

今からセキュリティーグループなども出来るようにします。

**Comment by Metallion** [comment]
`ip_address`の設定も出来るようになりました。https://github.com/axsh/wakame-vdc/commit/f74c647bb4b1c04785cba2d0af0ae3be2a9752e6

でも現在のAPIバグのせいで、`ip_address`使うときに、必ず`host_node_id`の設定入れないと動きません。これはterraformのバグじゃなくて、APIのバグなので、別ブランチと別issueで直します。

**Comment by Metallion** [comment]
Security Groupsも使えるようになりました。https://github.com/axsh/wakame-vdc/commit/ddeb38fa859bebaeb5a73be181a44ea33e33137e

まだコードが汚いけど、とりあえず動きます。これからリファクターします。
