### ISSUE TITLE
Feature IP address assignment retention period

### ISSUE THREAD

**Issue by unakatsuo** [axsh/wakame-vdc#95]
This change aims to improve IP address assignment strategy to avoid to re-use same IP addresses as long as possible.

Assume 192.168.1.0/24 network and .2-254 is given as dynamic range. Then the user will start three instances in the network but second one will be terminated before the third one starts.

```
Step1.
i-00001 

Step2.
i-00001
i-00002

Step3.
i-00001
i-00002 -> terminate

Step4.
i-00001
i-00003
```

Following describes how the address is provisioned at this moment:

```
1.
i-00001: 192.168.1.2

2.
i-00001: 192.168.1.2
i-00002: 192.168.1.3

3.
i-00001: 192.168.1.2

4.
i-00001: 192.168.1.2
i-00003: *192.168.1.3
```

The descending order assignment is expected normally as below:

```
1.
i-00001: 192.168.1.2

2.
i-00001: 192.168.1.2
i-00002: 192.168.1.3

3.
i-00001: 192.168.1.2

4.
i-00001: 192.168.1.2
i-00003: *192.168.1.4
```

** Changes

1. Add retention period field to networks table.
2. Update Models::IpLease#iplease or around where provision IP address

**Comment by Metallion** [comment]
No longer an issue at this time.
